---
title: 'Metadata Wrangling!'
author: "Jackson Hughes"
date: "9/13/2021"
output: 
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
```

```{r}
metadata_0 <- read_csv("All Metadata CHEM 142 MC.csv")
```

```{r}
metadata_1 <- remove_empty(metadata_0)
metadata_2 <- metadata_1 %>% add_row(.before = 1)
```

```{r}
metadata_2[1,1] <- 1
metadata_2[1,2] <- "C"
metadata_3 <- metadata_2 %>% 
  rename("X1" = "1") %>% 
  rename("X2" = "C")
```

```{r}
for (i in 1:nrow(metadata_3)) {
  if(str_detect(metadata_3[[2]][[i]], "^[[:alpha:]]{1}$")){
    metadata_3[[3]][[i]] <- metadata_3[[2]][[i]]
    metadata_3[[2]][[i]] <- metadata_3[[1]][[i]]}
}

for (i in 1:nrow(metadata_3)) {
  if(str_detect(metadata_3[[2]][[i]], "^[[:digit:]]{1,3}$")){
    metadata_3[[2]][[i]] <- "answer"}
}
```

```{r}
tibble(metadata_3)
```

### Repeat question numbers down dataset

```{r}
for (i in 1:nrow(metadata_3)) {
  if(str_detect(metadata_3[[1]][[i]], "^[[:digit:]]{1,3}$")){
    current_digit <- metadata_3[[1]][[i]]
    j <- 1
    while (is.na(metadata_3[[1]][[i+j]])) {
      metadata_3[[1]][[i+j]] <- current_digit
      j <- j+1
      # cat("i = ", i, "current_digit = ", current_digit, "j = ", j, "\n")
      # & (i <= nrow(metadata_3)-8)
    }
  }
}
```

### Make data wide

```{r}
metadata_4 <- pivot_wider(metadata_3, names_from = X2, values_from = X3) %>% 
  rename("question" = "X1")
## Yayy!
```
